"""initial

Revision ID: 4a8c76366651
Revises: 
Create Date: 2026-05-10 02:10:06.976325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a8c76366651'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('superficie_km2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('indicador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('poblacion_total', sa.Integer(), nullable=True),
    sa.Column('poblacion_2005', sa.Integer(), nullable=True),
    sa.Column('densidad_hab_km2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pct_hombres', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pct_mujeres', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pct_urbana', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pct_rural', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pct_indigena', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('esperanza_vida', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('analfabetismo_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('acceso_agua_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('acceso_saneamiento_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecundidad', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('crecimiento_anual_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('idh_ranking', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departamento_id', 'anio', name='uq_indicador_depto_anio')
    )
    op.create_index('idx_indicador_anio', 'indicador', ['anio'], unique=False)
    op.create_index('idx_indicador_depto', 'indicador', ['departamento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_indicador_depto', table_name='indicador')
    op.drop_index('idx_indicador_anio', table_name='indicador')
    op.drop_table('indicador')
    op.drop_table('departamento')
    op.drop_table('region')
    # ### end Alembic commands ###
