"""add cabecera to departamento

Revision ID: 9f027ebbb729
Revises: b8e5c02f7d19
Create Date: 2026-09-18 16:03:12.700679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f027ebbb729'
down_revision: Union[str, None] = 'b8e5c02f7d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departamento', sa.Column('cabecera', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departamento', 'cabecera')
    # ### end Alembic commands ###
